//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextAdventure.UnitTests.Engine.Serializers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerializerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerializerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextAdventure.UnitTests.Engine.Serializers.SerializerResources", typeof(SerializerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;world id=&quot;9846b8bf-6312-4dd0-a70b-022d1ea2d65e&quot; version=&quot;1&quot; title=&quot;Title&quot;&gt;
        ///	&lt;startingPlayer id=&quot;e64d573a-20e2-4f26-9367-3687b250917b&quot; boardId=&quot;be68b2a8-8b40-440f-a93f-6c5986a000bc&quot; coordinate=&quot;10,10&quot;&gt;
        ///		&lt;character symbol=&quot;2&quot; foregroundColor=&quot;0.5,0.7,0.9,1&quot; backgroundColor=&quot;0,0,0,0&quot; /&gt;
        ///		&lt;actorInstanceTouchedPlayerEventHandler type=&quot;TextAdventure.UnitTests.Engine.Serializers.Xml.WorldSerializerTester+ActorInstanceTouchedPlayerEventHandler, TextAdventure.UnitTests&quot; /&gt;
        ///	&lt;/startingPlayer&gt;
        ///	&lt;board id=&quot;be68 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
